### ISSUE TITLE
Http2 protocol not handled correctly, and not recognize libnghttp2.so by ffi.

### ISSUE THREAD

**Issue by xpader** [amphp/hpack#12]
Version amphp/http-client 4.6.2.
PHP Version: 8.0, 8.1

Some request from out linux server (Ubuntu 20.04) always return `Amp\Http\Client\Connection\Http2ConnectionException: The HTTP/2 connection from '192.168.1.112:41306' to '****:443' closed`, but from local develop machine (MacOS 13.4) always success.

After some dig, I found that reason is local machine can correct locate `libnghttp2.dylib` to use `HPackNgHttp2`, but server can't locate `libnghttp2.so`.

By apt, I found that libnghttp2 package is `libnghttp2-14` in server, and files list:

```
dpkg -L libnghttp2-14
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libnghttp2.so.14.19.0
/usr/share
/usr/share/doc
/usr/share/doc/libnghttp2-14
/usr/share/doc/libnghttp2-14/AUTHORS
/usr/share/doc/libnghttp2-14/README.rst.gz
/usr/share/doc/libnghttp2-14/changelog.Debian.gz
/usr/share/doc/libnghttp2-14/copyright
/usr/lib/x86_64-linux-gnu/libnghttp2.so.14
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libnghttp2.so.14.19.0
/usr/share
/usr/share/doc
/usr/share/doc/libnghttp2-14
/usr/share/doc/libnghttp2-14/AUTHORS
/usr/share/doc/libnghttp2-14/README.rst.gz
/usr/share/doc/libnghttp2-14/changelog.Debian.gz
/usr/share/doc/libnghttp2-14/copyright
/usr/lib/x86_64-linux-gnu/libnghttp2.so.14
```

There is no `libnghttp2.so` file in server, only `libnghttp2.so.14`, when I change `libnghttp2.so` to `libnghttp2.so.14` in here: https://github.com/amphp/hpack/blob/cf4f1663e9fd58f60258c06177098655ca6377a5/src/Internal/HPackNghttp2.php#L73
It's worked.

There's two problem here:
- HPackNative not correctly handle http2 protocol, makes HTTP/2 connection closed error.
- FFI can not locate the right libnghttp2.so.* file, fallback to HPackNative.

GPT give me a answer that we can create a symbol link to real libnghttp2.so.* file or use `ldconfig -p | grep 'libnghttp2.so' | awk '{print $4}'` to locate it.

**Comment by trowski** [comment]
I fixed the `Cannot instantiate FFI\CData of zero size` issue in the current branch. I'll tag a bugfix release for that change while we find some time to investigate the other issue.

**Comment by xpader** [comment]
I have a request to reproducer this error, but the example include some sensitive infomation, how could I send this to you?

**Comment by xpader** [comment]
FFI memory leak very exaggerated, and memory is leak outer of PHP memory manager.
The memory info from `memory_get_usage()` is very normal, but in system, php process memory is now 4G after running 2 days. Even set memory_limit for php, process still not exit after memory exceed.

**Comment by kelunik** [comment]
You can send it to `me@kelunik.com`.

**Comment by xpader** [comment]
Mail has been sent to you, any updates?

**Comment by kelunik** [comment]
@xpader Do you use the `proxy-authenticate` header?

**Comment by kelunik** [comment]
@xpader Yes, I received it, I should have had another look at it before writing that comment. Anyway, I could reproduce the issue and have fixed it now. Thanks for reporting!
